name: Package non release tag (like release tag but with a custom suffix 'v0.0.0-<suffix>')

on:
  push:
    branches:
      - main

jobs:
  go:
    name: Go
    uses: ./.github/workflows/go.yaml
    with:
      is_docker_build: false

  docker_build_push:
    name: Docker build
    needs: [go]
    uses: ./.github/workflows/docker_build_push.yaml
    secrets: inherit # pass all secrets
    with:
      branch_name: ${{ github.ref_name }}
